# .github/workflows/main.yml

name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Frontend Job
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: ./frontend/build

  # Backend Job
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./backend

      - name: Run Backend Tests
        run: mvn test
        working-directory: ./backend

      - name: Build Docker Image for Backend
        run: docker build -t fitness-backend:latest .
        working-directory: ./backend

      - name: Upload Backend Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: ./backend/target/*.jar

  # Deployment Job
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Frontend Build
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: ./frontend/build

      - name: Download Backend Build
        uses: actions/download-artifact@v2
        with:
          name: backend-build
          path: ./backend/target

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fitness-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fitness-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/fitness-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fitness-backend:latest

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Replace this with deployment commands for ECS, EKS, or EC2
          echo "Deploying to AWS"
